apiVersion: v2
appVersion: '1.0'
description: A Helm chart for justicetranscribe-frontend App
name: justicetranscribe-frontend
home: https://github.com/hmcts/justicetranscribe-frontend
version: 0.0.11
dependencies:
  - name: nodejs
    version: 3.2.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
